### ISSUE TITLE
cannot load nvcuda.dll

### ISSUE THREAD

**Issue by driesj** [Raveler/ffmpeg-cpp#5]
The build was successful, but when I've tried to run the demo.cpp it crashed.
in the demo.exe i've got following feedback:
`Encoding video as H264 on Nvidia GPU...
Applying filter transpose=cclock[middle];[middle]vignette to video...
Pulling video from samples/carphone.h264...
[h264_nvenc @ 000001f8d00602c0] Cannot load nvcuda.dll
Could not open codecContext for codec: Operation not permitted`
when going back to VS I see that the error got catched by the FFmpegException and output is the following:

```
'demo.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
The thread 0x1960 has exited with code 0 (0x0).
Exception thrown at 0x00007FFEB1B0A388 in demo.exe: Microsoft C++ exception: ffmpegcpp::FFmpegException at memory location 0x0000005F2E0FC420.
Exception thrown at 0x00007FFEB1B0A388 in demo.exe: Microsoft C++ exception: ffmpegcpp::FFmpegException at memory location 0x0000005F2E0FF750.
Unhandled exception at 0x00007FFEB1B0A388 in demo.exe: Microsoft C++ exception: ffmpegcpp::FFmpegException at memory location 0x0000005F2E0FF750.

The program '[15140] demo.exe' has exited with code 0 (0x0).
```

**Comment by driesj** [comment]
This is because I had outputVideoCodec set as "H264", which only works with Nvidia hardware. changing to VP9 or NONE made it work.

**Comment by Raveler** [comment]
Right, thanks! This is because the H264 encoder of ffmpeg internally uses nvenc, which is a hardware-based encoder available in nVidia GPU's.

It is very easy to write a Codec that will use libx264 (the software encoder) instead. Just edit H264NVEncCodec.cpp line 7 and replace "h264_nvenc" with "libx264". You also need to make sure you set a valid preset, since the default preset used in demo.cpp is "hq", which is not supported by libx264. If you run the example after changing the codec to libx264, it will give a nice error with all available legal presets.

**Comment by driesj** [comment]
Thanks, this works very well!
